# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5433/wordle?currentSchema=wordle&user=postgres&password=123}
#db.url=jdbc:postgresql://localhost:5433/wordle
#db.username=postgres
#db.password=123

# Hibernate Configuration
jpa.packages-to-scan=ru.wordle.infrastructure.entity
hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.jdbc.lob.non_contextual_creation=true
liqui.enabled=true
liqui.default-schema=wordle